### ISSUE TITLE
Add tests for different postBuyOrder cases

### ISSUE THREAD

**Issue by gorgos** [PoolX-DutchX/PoolX-Contract#15]
1) postBuyOrder done immediately after auctionStart
2) postBuyOrder done few hours after auctionStart -> pool checks refunded buy token amounts and redistributes them to the users proportionally to their buy token contributions when user claims his funds
3) postBuyOrder not done -> omit claiming buy funds from dutchx, buy tokens will be leftover as in case 2) and can be withdrawn via user claiming funds

**Comment by gustavoguimaraes** [comment]
Also, ensure that both token 1 and token 2 are claimed properly from buy and sell side.

**Comment by gustavoguimaraes** [comment]
@elektronaut0815 Can you take this issue?

**Comment by gorgos** [comment]
1. postBuyOrder done immediately after auctionStart
2. postBuyOrder done few hours after auctionStart -> pool checks refunded buy token amounts and redistributes them to the users proportionally to their buy token contributions when user claims his funds
    2.1 other non pool-users have participated meanwhile in the auction
    2.2 no others have participated
3. postBuyOrder not done -> omit claiming buy funds from dutchx, buy tokens will be leftover as in case 2) and can be withdrawn via user claiming funds
    3.1 other non pool-users have finished the auction successfully meanwhile
    3.2 the auction failed. what actually happens in that case to the auction?

**Comment by gustavoguimaraes** [comment]
This looks like it is done.
